#!/bin/sh
set -e
# see Debian bugs #996954, #962300, #990188
patch -p1 << 'EOF'
diff -Nru dmraid-1.0.0.rc16/debian/dmraid.postinst dmraid-1.0.0.rc16/debian/dmraid.postinst
--- dmraid-1.0.0.rc16/debian/dmraid.postinst	2017-08-30 23:28:37.000000000 +0200
+++ dmraid-1.0.0.rc16/debian/dmraid.postinst	2021-12-26 15:45:13.000000000 +0100
@@ -9,7 +9,7 @@
 	    update-initramfs -u
     fi
     # Activate existing arrays now.
-    udevadm trigger --subsystem-match=block --action=change
+    udevadm trigger --subsystem-match=block --action=change || true
 
     if [ -f /etc/init.d/dmraid ]; then
   	update-rc.d -f dmraid remove
EOF
