#!/bin/sh
set -e
# https://bugs.debian.org/1118195
patch -p1 << 'EOF'
--- a/debian/firmware-misc-nonfree.install	2025-10-15 18:02:57.000000000 +0200
+++ b/debian/firmware-misc-nonfree.install	2025-10-17 23:36:45.000000000 +0200
@@ -88,6 +88,8 @@
 debian/build/install/amphion/vpu/vpu_fw_imx8_dec.bin /usr/lib/firmware/amphion/vpu
 debian/build/install/amphion/vpu/vpu_fw_imx8_enc.bin /usr/lib/firmware/amphion/vpu
 debian/build/install/arm/mali/arch10.8/mali_csffw.bin /usr/lib/firmware/arm/mali/arch10.8
+debian/build/install/arm/mali/arch10.10/mali_csffw.bin /usr/lib/firmware/arm/mali/arch10.10
+debian/build/install/arm/mali/arch10.12/mali_csffw.bin /usr/lib/firmware/arm/mali/arch10.12
 debian/build/install/as102_data1_st.hex /usr/lib/firmware/.
 debian/build/install/as102_data2_st.hex /usr/lib/firmware/.
 debian/build/install/brcm/BCM-0a5c-6410.hcd /usr/lib/firmware/brcm
EOF

# fixup ./debian/control.md5sum or otherwise the packaging will try to
# regenerate the control files using debian/bin/gencontrol.py
md5=$(printf 'Source: firmware-nonfree\nVersion: %s\n' "$(dpkg-parsechangelog -SVersion)" | md5sum | awk '{print $1}')
sed -i "s#^.*  debian/build/version-info\$#$md5  debian/build/version-info#" ./debian/control.md5sum
