#!/bin/sh
set -e
patch -p1 << 'EOF'
diff --git a/functions b/functions
index a2e2b31..5899e59 100644
--- a/functions
+++ b/functions
@@ -789,13 +789,12 @@ if [ -L "$kfile" ]; then
 	kfile=$(readlink -e "$kfile")
 fi
 
-if [ -d /sys/firmware/efi ]; then
-	# skipping when detect EFI
-	echo "System running in EFI mode, skipping."
-	exit 0
-fi
-
 if ! check_supported "$machine"; then
+	# do nothing if an unsupported platform is booted from EFI
+	if [ -d /sys/firmware/efi ]; then
+		echo "Unsupported platform on EFI system, doing nothing."
+		exit 0
+	fi
 	error "Unsupported platform '$machine'."
 fi
 
EOF
