#!/bin/sh
# https://salsa.debian.org/kernel-team/linux-base/-/merge_requests/14/diffs
# no changes bump for Esther
patch -p1 << 'END'
From fe31a3e39e975027f10e3786620261476681078d Mon Sep 17 00:00:00 2001
From: Ben Hutchings <benh@debian.org>
Date: Tue, 20 May 2025 00:40:29 +0200
Subject: [PATCH 1/2] Clarify that version parameters are not package version
 strings

Currently linux-version(1) is explicit that the version parameters are
kernel version strings and not package version strings.  The other
manual pages and help texts are not quite as explicit.

Bastian suggested using the term 'release', which would be consistent
with what 'uname -r' calls this string but not with common usage.
Instead:

* Rename the VERSION{,1,2} metavariables to KERNEL-VER{,-1,-2}
* Add 'not the package version' to the descriptions of these
  parameters
---
 bin/linux-check-removal     |  8 ++++----
 bin/linux-update-symlinks   |  6 +++---
 bin/linux-version           |  8 ++++----
 man/linux-check-removal.1   |  8 ++++----
 man/linux-update-symlinks.1 | 12 ++++++------
 man/linux-version.1         |  8 ++++----
 6 files changed, 25 insertions(+), 25 deletions(-)

diff --git a/bin/linux-check-removal b/bin/linux-check-removal
index 8552f5b..33a85b9 100755
--- a/bin/linux-check-removal
+++ b/bin/linux-check-removal
@@ -25,15 +25,15 @@ use POSIX ();
 sub usage {
     my $fh = shift;
     print $fh (<< "EOT");
-Usage: $0 VERSION
+Usage: $0 KERNEL-VER
 
 This command is intended to be called from the prerm maintainer scripts
 of Linux kernel packages.
 
-The VERSION argument must be the kernel version string as shown by
-'uname -r' and used in filenames.
+The KERNEL-VER argument must be the kernel version string as shown by
+'uname -r' and used in filenames, not the package version.
 
-If the currently running kernel matches VERSION, linux-check-removal
+If the currently running kernel matches KERNEL-VER, linux-check-removal
 will normally prompt the user to confirm this potentially dangerous
 action and will fail if the user chooses to abort.  However, if the
 current environment is in a chroot or container, or if debconf
diff --git a/bin/linux-update-symlinks b/bin/linux-update-symlinks
index 8b7198c..b064113 100755
--- a/bin/linux-update-symlinks
+++ b/bin/linux-update-symlinks
@@ -26,15 +26,15 @@ use DebianLinux qw(image_stem image_list read_kernelimg_conf version_cmp);
 sub usage {
     my $fh = shift;
     print $fh (<< "EOT");
-Usage: $0 {install|upgrade|remove} VERSION IMAGE-PATH
+Usage: $0 {install|upgrade|remove} KERNEL-VER IMAGE-PATH
 
 This command is intended to be called from the postinst and postrm
 maintainer scripts of Linux kernel packages.  The postinst script must
 pass the first argument 'install' or 'upgrade' depending on whether a
 fresh installation or an upgrade has taken place.
 
-The VERSION argument must be the kernel version string as shown by
-'uname -r' and used in filenames.
+The KERNEL-VER argument must be the kernel version string as shown by
+'uname -r' and used in filenames, not the package version.
 
 The IMAGE-PATH argument must be the absolute filename of the kernel
 image.
diff --git a/bin/linux-version b/bin/linux-version
index 6383eda..9dc28f4 100755
--- a/bin/linux-version
+++ b/bin/linux-version
@@ -24,12 +24,12 @@ use DebianLinux qw(version_cmp image_list);
 sub usage {
     my $fh = shift;
     print $fh (<< "EOT");
-Usage: $0 compare VERSION1 OP VERSION2
-       $0 sort [--reverse] [VERSION1 VERSION2 ...]
+Usage: $0 compare KERNEL-VER-1 OP KERNEL-VER-2
+       $0 sort [--reverse] [KERNEL-VER-1 KERNEL-VER-2 ...]
        $0 list [--paths]
 
-The version arguments should be kernel version strings as shown by
-'uname -r' and used in filenames.
+The version arguments must be kernel version strings as shown by
+'uname -r' and used in filenames, not package versions.
 
 The valid comparison operators are: lt le eq ge gt
 EOT
diff --git a/man/linux-check-removal.1 b/man/linux-check-removal.1
index b78a588..1ac7cf0 100644
--- a/man/linux-check-removal.1
+++ b/man/linux-check-removal.1
@@ -3,15 +3,15 @@
 linux\-check\-removal \- check whether removal of a kernel is safe
 .SH SYNOPSIS
 .HP
-.BI linux\-check\-removal \ VERSION
+.BI linux\-check\-removal \ KERNEL\-VER
 .SH DESCRIPTION
 \fBlinux\-check\-removal\fR is intended to be called from the prerm
 maintainer scripts of Linux kernel packages.
 .PP
-The \fIVERSION\fR argument must be the kernel version string as shown by
-\fBuname -r\fR and used in filenames.
+The \fIKERNEL\-VER\fR argument must be the kernel version string as shown by
+\fBuname -r\fR and used in filenames, not the package version.
 .PP
-If the currently running kernel matches \fIVERSION\fR,
+If the currently running kernel matches \fIKERNEL\-VER\fR,
 \fBlinux\-check\-removal\fR normally prompts the user to confirm
 this potentially dangerous action and fails if the user chooses to
 abort.  There are two exceptions to this behaviour:
diff --git a/man/linux-update-symlinks.1 b/man/linux-update-symlinks.1
index c6ea4dc..ad134c3 100644
--- a/man/linux-update-symlinks.1
+++ b/man/linux-update-symlinks.1
@@ -5,7 +5,7 @@ linux\-update\-symlinks \- maintain symlinks to default kernel and initramfs
 .SH SYNOPSIS
 .HP
 .BR linux\-update\-symlinks \ { install | upgrade | remove }
-.I VERSION IMAGE\-PATH
+.I KERNEL\-VER IMAGE\-PATH
 
 .SH DESCRIPTION
 \fBlinux\-update\-symlinks\fR is intended to be called from the
@@ -14,8 +14,8 @@ postinst script must pass the first argument \fBinstall\fR or
 \fBupgrade\fR depending on whether a fresh installation or an upgrade
 has taken place.
 .PP
-The \fIVERSION\fR argument must be the kernel version string as shown by
-\fBuname -r\fR and used in filenames.
+The \fIKERNEL\-VER\fR argument must be the kernel version string as shown by
+\fBuname -r\fR and used in filenames, not the package version.
 .PP
 The \fIIMAGE\-PATH\fR argument must be the absolute filename of the
 kernel image.
@@ -45,7 +45,7 @@ If symlink maintenance is disabled, \fBlinux\-update\-symlinks\fR does
 nothing, successfully.  Otherwise it makes a list of kernel versions
 in decreasing order of priority:
 .IP \(bu 2
-The given \fIVERSION\fR, if the first argument is \fBinstall\fR
+The given \fIKERNEL\-VER\fR, if the first argument is \fBinstall\fR
 .IP \(bu 2
 The current primary default version, if it exists and is not already
 listed
@@ -54,7 +54,7 @@ The current secondary default version, if it exists and is not already
 listed
 .IP \(bu 2
 All other versions whose files are installed, excluding the specified
-\fIVERSION\fR if the first argument is \fBremove\fR, in decreasing
+\fIKERNEL\-VER\fR if the first argument is \fBremove\fR, in decreasing
 version order
 .PP
 The top two entries on the list are the new primary and secondary
@@ -68,7 +68,7 @@ versions and it removes the default symlinks.
 .TP
 .IR INITRD
 When the first argument is \fBinstall\fR or \fBupgrade\fR,
-\fBlinux\-update\-symlinks\fR assumes that the given \fIVERSION\fR
+\fBlinux\-update\-symlinks\fR assumes that the given \fIKERNEL\-VER\fR
 will use an initramfs unless this variable is set to \fBNo\fR.
 
 .SH FILES
diff --git a/man/linux-version.1 b/man/linux-version.1
index 3ca7047..fdc420d 100644
--- a/man/linux-version.1
+++ b/man/linux-version.1
@@ -3,10 +3,10 @@
 linux\-version \- operate on Linux kernel version strings
 .SH SYNOPSIS
 .HP
-.BI linux\-version\ compare \ VERSION1\ OP\ VERSION2
+.BI linux\-version\ compare \ KERNEL\-VER\-1\ OP\ KERNEL\-VER\-2
 .HP
 .BR linux\-version\ sort \ [ \-\-reverse ]
-.RI [ VERSION1\ VERSION2 \ ...]
+.RI [ KERNEL\-VER\-1\ KERNEL\-VER\-2 \ ...]
 .HP
 .BR linux\-version\ list \ [ \-\-paths ]
 .SH DESCRIPTION
@@ -16,13 +16,13 @@ These version strings do not follow the same rules as Debian package
 version strings and should not be compared as such or as arbitrary
 strings.
 .TP
-.BI compare \ VERSION1\ OP\ VERSION2
+.BI compare \ KERNEL\-VER\-1\ OP\ KERNEL\-VER\-2
 Compare version strings, where \fIOP\fP is a binary
 operator. \fBlinux\-version\fP returns success (zero result) if the
 specified condition is satisfied, and failure (nonzero result)
 otherwise.  The valid operators are: \fBlt le eq ne ge gt\fP
 .TP
-\fBsort\fR [\fB\-\-reverse\fR] [\fIVERSION1 VERSION2\fR ...]
+\fBsort\fR [\fB\-\-reverse\fR] [\fIKERNEL\-VER\-1 KERNEL\-VER\-2\fR ...]
 Sort the given version strings and print them in order from lowest to
 highest.  If the \fB\-\-reverse\fR option is used, print them in order
 from highest to lowest.
-- 
GitLab


From 1075f700ca0025af9dd18ca1eba7affd725a3c97 Mon Sep 17 00:00:00 2001
From: Ben Hutchings <benh@debian.org>
Date: Sat, 3 May 2025 03:51:05 +0200
Subject: [PATCH 2/2] Add linux-run-hooks command for use by package maintainer
 scripts

Add a linux-run-hooks command as a fairly simple wrapper around
run-parts.  This is intended to be used by maintainer scripts instead
of directly calling run-parts.  The benefits of that are:

- It supports use of multiple hooks directories (under /etc/kernel and
  /usr/share/kernel) if debianutils is new enough, but still works
  with older versions if only one hooks directory is present.

- The arguments to hooks are documented and the number of arguments is
  validated.

- The same logic can be shared with Ubuntu and any other derivatives
  that have their own packaging.
---
 bin/linux-run-hooks        | 116 +++++++++++++++++++++++++++++++++++++
 debian/linux-base.install  |   1 +
 debian/linux-base.manpages |   1 +
 man/linux-run-hooks.1      |  36 ++++++++++++
 5 files changed, 155 insertions(+)
 create mode 100755 bin/linux-run-hooks
 create mode 100644 man/linux-run-hooks.1

diff --git a/bin/linux-run-hooks b/bin/linux-run-hooks
new file mode 100755
index 0000000..d2f1932
--- /dev/null
+++ b/bin/linux-run-hooks
@@ -0,0 +1,128 @@
+#!/usr/bin/perl
+
+# Copyright 2025 Ben Hutchings
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+use strict;
+use warnings;
+
+sub usage {
+    my $fh = shift;
+    print $fh (<< "EOT");
+Usage: $0 image MAINT-SCRIPT KERNEL-VER IMAGE-PATH -- MAINT-PARAMS ...
+       $0 headers MAINT-SCRIPT KERNEL-VER -- MAINT-PARAMS ...
+
+This command is intended to be called from the maintainer scripts of
+Linux kernel image and headers packages.  It executes hooks installed
+in the appropriate subdirectories of /etc/kernel and
+/usr/share/kernel.
+
+The MAINT-SCRIPT argument must be the name of the maintainer script:
+preinst, postinst, prerm, or postrm.
+
+The KERNEL-VER argument must be the kernel version string as shown by
+'uname -r' and used in filenames, not the package version.
+
+The IMAGE-PATH argument must be the absolute filename of the kernel
+image.
+
+The MAINT-PARAMS arguments must be the parameters received by the
+maintainer script.
+EOT
+}
+
+sub usage_error {
+    usage(*STDERR{IO});
+    exit 2;
+}
+
+sub run_hooks {
+    my ($type, $hook_args, $maint_params) = @_;
+    my @hook_dirs;
+
+    # run-parts handling of directory arguments differs between
+    # versions of debianutils:
+    #
+    # <= 5.20: must pass exactly 1 existing directory name
+    # == 5.21: must pass 1 or more existing directory names
+    # >= 5.22: must pass 1 or more directory names; warning
+    #          emitted for non-existent directories
+    #
+    # So, to be backward-compatible, we only pass directories that
+    # exist and do not run it at all if none exist.  We rely on
+    # packages not to install hooks under /usr/share/kernel without a
+    # dependency or other guarantee that debianutils is >= 5.21.
+    for my $dir ("/etc/kernel/$type.d",
+		 "/usr/share/kernel/$type.d") {
+	push @hook_dirs, $dir if -d $dir;
+    }
+    if (@hook_dirs == 0) {
+	exit 0;
+    }
+
+    $ENV{'DEB_MAINT_PARAMS'} = join(' ', @$maint_params);
+    exec 'run-parts', '--debug', '--exit-on-error',
+	map({"--arg=$_"} @$hook_args),
+	@hook_dirs;
+
+    # run-parts could not be executed. exec already reported an error
+    # message, so just return failure.
+    exit 1;
+}
+
+if (@ARGV == 0) {
+    usage_error();
+}
+if ($ARGV[0] eq 'help' or grep({$_ eq '--help'} @ARGV)) {
+    usage(*STDOUT{IO});
+    exit 0;
+}
+
+my ($pkg_type, $script_type) = @ARGV;
+
+# support the old interface from
+# https://salsa.debian.org/kernel-team/linux-base/-/merge_requests/14
+# until everybody has upgraded
+if ($pkg_type =~ /^(?:pre|post)(?:inst|rm)$/ && @ARGV == 4) {
+	run_hooks($ARGV[0], [$ARGV[2], $ARGV[3]], [split /\s+/, $ARGV[1]]);
+	exit 1;
+} elsif ($pkg_type eq 'headers_postinst' && @ARGV == 3) {
+	run_hooks($ARGV[0], [$ARGV[2]], [split /\s+/, $ARGV[1]]);
+	exit 1;
+}
+
+if (!defined($pkg_type)
+    or ($pkg_type ne 'image' and $pkg_type ne 'headers')
+    or !defined($script_type)
+    or ($script_type !~ /^(?:pre|post)(?:inst|rm)$/)) {
+    usage_error();
+}
+my ($hook_type, $n_hook_args);
+if ($pkg_type eq 'image') {
+    $hook_type = $script_type;
+    $n_hook_args = 2;
+} else {
+    $hook_type = "${pkg_type}_${script_type}";
+    $n_hook_args = 1;
+}
+my ($arg_sep_index) = grep({ $ARGV[$_] eq '--' } 2..$#ARGV);
+if (!defined($arg_sep_index)
+    or $arg_sep_index != 2 + $n_hook_args) {
+    usage_error();
+}
+
+run_hooks($hook_type,
+	  [@ARGV[2 .. $arg_sep_index-1]],
+	  [@ARGV[$arg_sep_index+1 .. $#ARGV]]);
diff --git a/debian/linux-base.install b/debian/linux-base.install
index 90acfeb..e0b1726 100644
--- a/debian/linux-base.install
+++ b/debian/linux-base.install
@@ -1,4 +1,5 @@
 bin/linux-check-removal usr/bin
+bin/linux-run-hooks usr/bin
 bin/linux-update-symlinks usr/bin
 bin/linux-version usr/bin
 lib/DebianLinux.pm usr/share/perl5
diff --git a/debian/linux-base.manpages b/debian/linux-base.manpages
index cd0fcaf..8dabdc2 100644
--- a/debian/linux-base.manpages
+++ b/debian/linux-base.manpages
@@ -2,5 +2,6 @@ man/kernel-img.conf.5
 man/kernel-img.conf.de.5
 man/kernel-img.conf.fr.5
 man/linux-check-removal.1
+man/linux-run-hooks.1
 man/linux-update-symlinks.1
 man/linux-version.1
diff --git a/man/linux-run-hooks.1 b/man/linux-run-hooks.1
new file mode 100644
index 0000000..4fb216d
--- /dev/null
+++ b/man/linux-run-hooks.1
@@ -0,0 +1,36 @@
+.TH LINUX-RUN-HOOKS 1 "3 May 2025"
+.SH NAME
+linux\-run\-hooks \- run package installation or removal hooks
+
+.SH SYNOPSIS
+\fBlinux\-run\-hooks image\fB \fIMAINT\-SCRIPT KERNEL\-VER IMAGE\-PATH\fR
+                \fB--\fR \fIMAINT\-PARAMS\fR ...
+.PP
+\fBlinux\-run\-hooks headers\fB \fIMAINT\-SCRIPT KERNEL\-VER\fR
+                \fB--\fR \fIMAINT\-PARAMS\fR ...
+.SH DESCRPTION
+\fBlinux\-run\-hooks\fR is intended to be called from the maintainer
+scripts of Linux kernel image and headers packages.  It uses the
+\fBrun-parts\fR command to execute hooks installed in the appropriate
+subdirectories of \fB/etc/kernel\fR and \fB/usr/share/kernel\fR.
+.PP
+Each maintainer script in a kernel image package should call this
+command with its script type as the first argument.  The postinst
+script in a headers package should call it with \fBheaders_postinst\fR
+as the first argument.
+.PP
+The \fIMAINT\-SCRIPT\fR argument must be the name of the maintainer
+script: \fBpreinst\fR, \fBpostinst\fR, \fBprerm\fR, or \fBpostrm\fR.
+.PP
+The \fIKERNEL\-VER\fR argument must be the kernel version string as
+shown by \fBuname -r\fR and used in filenames, not the package
+version.
+.PP
+The \fIIMAGE\-PATH\fR argument must be the absolute filename of the
+kernel image.
+.PP
+The \fIMAINT-PARAMS\fR arguments must be the parameters received by
+the maintainer script.
+.SH AUTHOR
+\fBlinux\-run\-hooks\fR and this manual page were written by Ben
+Hutchings as part of the Debian \fBlinux\-base\fR package.
-- 
GitLab
END
