#!/bin/sh
# https://salsa.debian.org/kernel-team/linux-base/-/merge_requests/14/diffs
patch -p1 << 'END'
From 3b9e22a664b8fdcacda476a62aa721d8f39bf8c7 Mon Sep 17 00:00:00 2001
From: Ben Hutchings <benh@debian.org>
Date: Sat, 3 May 2025 03:51:05 +0200
Subject: [PATCH] Add linux-run-hooks command for use by package maintainer
 scripts

Add a linux-run-hooks command as a fairly simple wrapper around
run-parts.  This is intended to be used by maintainer scripts instead
of directly calling run-parts.  The benefits of that are:

- It supports use of multiple hooks directories (under /etc/kernel and
  /usr/share/kernel) if debianutils is new enough, but still works
  with older versions if only one hooks directory is present.

- The arguments to hooks are documented and the number of arguments is
  validated.

- The same logic can be shared with Ubuntu and any other derivatives
  that have their own packaging.
---
 bin/linux-run-hooks   | 94 +++++++++++++++++++++++++++++++++++++++++++
 debian/changelog      |  1 +
 man/linux-run-hooks.1 | 35 ++++++++++++++++
 3 files changed, 130 insertions(+)
 create mode 100755 bin/linux-run-hooks
 create mode 100644 man/linux-run-hooks.1

diff --git a/debian/linux-base.install b/debian/linux-base.install
index 90acfeb..62c509d 100644
--- a/debian/linux-base.install
+++ b/debian/linux-base.install
@@ -1,4 +1,5 @@
 bin/linux-check-removal usr/bin
 bin/linux-update-symlinks usr/bin
 bin/linux-version usr/bin
+bin/linux-run-hooks usr/bin
 lib/DebianLinux.pm usr/share/perl5
diff --git a/bin/linux-run-hooks b/bin/linux-run-hooks
new file mode 100755
index 0000000..6568f22
--- /dev/null
+++ b/bin/linux-run-hooks
@@ -0,0 +1,98 @@
+#!/usr/bin/perl
+
+# Copyright 2025 Ben Hutchings
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+use strict;
+use warnings;
+
+sub usage {
+    my $fh = shift;
+    print $fh (<< "EOT");
+Usage: $0 {preinst|postinst|prerm|postrm} MAINT-PARAMS VERSION IMAGE-PATH
+       $0 headers_postinst MAINT-PARAMS VERSION
+
+This command is intended to be called from the maintainer scripts of
+Linux kernel packages.  It executes hooks installed in the appropriate
+subdirectories of /etc/kernel and /usr/share/kernel.
+
+The MAINT-PARAMS must be the parameters received by the maintainer
+script, joined together with spaces.
+
+The VERSION argument must be the kernel version string as shown by
+'uname -r' and used in filenames.
+
+The IMAGE-PATH argument must be the absolute filename of the kernel
+image.
+EOT
+}
+
+sub usage_error {
+    usage(*STDERR{IO});
+    exit 2;
+}
+
+sub run_hooks {
+    my ($type, $maint_params, @hook_args) = @_;
+    my @hook_dirs;
+
+    # run-parts handling of directory arguments differs between
+    # versions of debianutils:
+    #
+    # <= 5.20: must pass exactly 1 existing directory name
+    # == 5.21: must pass 1 or more existing directory names
+    # >= 5.22: must pass 1 or more directory names; warning
+    #          emitted for non-existent directories
+    #
+    # So, to be backward-compatible, we only pass directories that
+    # exist and do not run it at all if none exist.  We rely on
+    # packages not to install hooks under /usr/share/kernel without a
+    # dependency or other guarantee that debianutils is >= 5.21.
+    for my $dir ("/etc/kernel/$type.d",
+		 "/usr/share/kernel/$type.d") {
+	push @hook_dirs, $dir if -d $dir;
+    }
+    if (@hook_dirs eq 0) {
+	exit 0;
+    }
+
+    $ENV{'DEB_MAINT_PARAMS'} = $maint_params;
+    exec 'run-parts', '--report', '--exit-on-error',
+	map({"--arg=$_"} @hook_args),
+	@hook_dirs;
+
+    # run-parts could not be executed. exec already reported an error
+    # message, so just return failure.
+    exit 1;
+}
+
+if (@ARGV == 0) {
+    usage_error();
+}
+
+print STDERR ("argv0: ". $ARGV[0]. "\n");
+print STDERR ("argv1: ". $ARGV[1]. "\n");
+print STDERR ("argv2: ". $ARGV[2]. "\n");
+print STDERR ("argv3: ". $ARGV[3]. "\n");
+my $type = $ARGV[0];
+if ($type eq 'help' or grep({$_ eq '--help'} @ARGV)) {
+    usage(*STDOUT{IO});
+    exit 0;
+} elsif ($type =~ /^(?:pre|post)(?:inst|rm)$/ && @ARGV == 3) {
+    run_hooks(@ARGV);
+} elsif ($type eq 'headers_postinst' && @ARGV == 2) {
+    run_hooks(@ARGV);
+}
+usage_error();
diff --git a/man/linux-run-hooks.1 b/man/linux-run-hooks.1
new file mode 100644
index 0000000..770d9ac
--- /dev/null
+++ b/man/linux-run-hooks.1
@@ -0,0 +1,35 @@
+.TH LINUX-RUN-HOOKS 1 "3 May 2025"
+.SH NAME
+linux\-run\-hooks \- run package installation or removal hooks
+
+.SH SYNOPSIS
+.HP
+.BR linux\-run\-hooks \ { preinst | postinst | prerm | postrm }
+.I MAINT\-PARAMS VERSION IMAGE\-PATH
+.HP
+.B linux\-run\-hooks headers_postinst
+.I MAINT\-PARAMS VERSION
+
+.SH DESCRPTION
+\fBlinux\-run\-hooks\fR is intended to be called from the maintainer
+scripts of Linux kernel packages.  It uses the \fBrun-parts\fR command
+to execute hooks installed in the appropriate subdirectories of
+\fB/etc/kernel\fR and \fB/usr/share/kernel\fR.
+.PP
+Each maintainer script in a kernel image package should call this
+command with its script type as the first argument.  The postinst
+script in a headers package should call it with \fBheaders_postinst\fR
+as the first argument.
+.PP
+The \fIMAINT-PARAMS\fR argument must be the parameters received by the
+maintainer script, joined together with spaces.
+.PP
+The \fIVERSION\fR argument must be the kernel version string as shown by
+\fBuname -r\fR and used in filenames.
+.PP
+The \fIIMAGE\-PATH\fR argument must be the absolute filename of the
+kernel image.
+
+.SH AUTHOR
+\fBlinux\-run\-hooks\fR and this manual page were written by Ben
+Hutchings as part of the Debian \fBlinux\-base\fR package.
-- 
GitLab
END
