#!/bin/sh
set -e
# #1104029
patch -p1 << 'EOF'
diff --git a/debian/patches/austriancoder/0001-etnaviv-isa-Add-txf-instruction.patch b/debian/patches/austriancoder/0001-etnaviv-isa-Add-txf-instruction.patch
new file mode 100644
index 00000000000..85a615eae17
--- /dev/null
+++ b/debian/patches/austriancoder/0001-etnaviv-isa-Add-txf-instruction.patch
@@ -0,0 +1,47 @@
+From 67c34b951622a8765fc94f237edbd65af6cc92a7 Mon Sep 17 00:00:00 2001
+From: Christian Gmeiner <cgmeiner@igalia.com>
+Date: Fri, 18 Apr 2025 23:35:20 +0200
+Subject: [PATCH 1/3] etnaviv: isa: Add txf instruction
+
+This instruction is used to implement texelfetch.
+
+Blob generates such txf's for
+dEQP-GLES3.functional.shaders.texture_functions.texelfetch.+
+
+Signed-off-by: Christian Gmeiner <cgmeiner@igalia.com>
+---
+ src/etnaviv/isa/etnaviv.xml      | 5 +++++
+ src/etnaviv/isa/tests/disasm.cpp | 1 +
+ 2 files changed, 6 insertions(+)
+
+diff --git a/src/etnaviv/isa/etnaviv.xml b/src/etnaviv/isa/etnaviv.xml
+index a337c1e9d07..42f551238bf 100644
+--- a/src/etnaviv/isa/etnaviv.xml
++++ b/src/etnaviv/isa/etnaviv.xml
+@@ -1359,6 +1359,11 @@ SPDX-License-Identifier: MIT
+ 	<pattern pos="80">1</pattern> <!-- OPCODE_BIT6 -->
+ </bitset>
+ 
++<bitset name="txf" extends="#instruction-tex-src0-src1-src2">
++	<pattern low="0" high="5">001001</pattern> <!-- OPC -->
++	<pattern pos="80">1</pattern> <!-- OPCODE_BIT6 -->
++</bitset>
++
+ <bitset name="imadlo0" extends="#instruction-alu-src0-src1-src2">
+ 	<pattern low="0" high="5">001100</pattern> <!-- OPC -->
+ 	<pattern pos="80">1</pattern> <!-- OPCODE_BIT6 -->
+diff --git a/src/etnaviv/isa/tests/disasm.cpp b/src/etnaviv/isa/tests/disasm.cpp
+index aa027618aa4..876af029866 100644
+--- a/src/etnaviv/isa/tests/disasm.cpp
++++ b/src/etnaviv/isa/tests/disasm.cpp
+@@ -166,6 +166,7 @@ INSTANTIATE_TEST_SUITE_P(Opcodes, DisasmTest,
+       disasm_state{ {0x00801036, 0x15400804, 0x01540050, 0x00000002}, "clamp0_max        t0.x___, u0.yyyy, u0.zzzz, void\n"},
+       disasm_state{ {0x0080103b, 0x00001804, 0x40000000, 0x00400028}, "iaddsat.s32       t0.x___, t1.xxxx, void, -t2.xxxx\n"},
+       disasm_state{ {0x01001008, 0x15400804, 0xd00100c0, 0x00000007}, "imod.u16          t0._y__, t0.yyyy, 1, void\n"},
++      disasm_state{ {0x07811009, 0x15001f20, 0x01ff00c0, 0x78021008}, "txf               t1, tex0.xyzw, t1.xyyy, t1.wwww, 4352\n"},
+       disasm_state{ {0x0080103c, 0x00001804, 0x40000140, 0x00000000}, "imullo0.s32       t0.x___, t1.xxxx, t2.xxxx, void\n"},
+       disasm_state{ {0x00801000, 0x00001804, 0x40010140, 0x00000000}, "imulhi0.s32       t0.x___, t1.xxxx, t2.xxxx, void\n"},
+       disasm_state{ {0x00801004, 0x00201804, 0x40010040, 0x00000000}, "idiv0.s16         t0.x___, t1.xxxx, t0.xxxx, void\n"},
+-- 
+2.49.0
+
diff --git a/debian/patches/austriancoder/0002-etnaviv-nir-Legalize-txf-lod-src.patch b/debian/patches/austriancoder/0002-etnaviv-nir-Legalize-txf-lod-src.patch
new file mode 100644
index 00000000000..74df15ce9ca
--- /dev/null
+++ b/debian/patches/austriancoder/0002-etnaviv-nir-Legalize-txf-lod-src.patch
@@ -0,0 +1,57 @@
+From 0d3fe9a6119cdb4516757f75918b1b62a2ed2954 Mon Sep 17 00:00:00 2001
+From: Christian Gmeiner <cgmeiner@igalia.com>
+Date: Fri, 18 Apr 2025 23:37:19 +0200
+Subject: [PATCH 2/3] etnaviv: nir: Legalize txf lod src
+
+The LOD must be a float, unlike the GLSL function, which expects an integer.
+
+Signed-off-by: Christian Gmeiner <cgmeiner@igalia.com>
+---
+ .../etnaviv/etnaviv_nir_lower_texture.c       | 25 +++++++++++++++++++
+ 1 file changed, 25 insertions(+)
+
+diff --git a/src/gallium/drivers/etnaviv/etnaviv_nir_lower_texture.c b/src/gallium/drivers/etnaviv/etnaviv_nir_lower_texture.c
+index d0462ead016..d20d175da79 100644
+--- a/src/gallium/drivers/etnaviv/etnaviv_nir_lower_texture.c
++++ b/src/gallium/drivers/etnaviv/etnaviv_nir_lower_texture.c
+@@ -26,6 +26,28 @@ lower_txs(nir_builder *b, nir_instr *instr, UNUSED void *data)
+    return true;
+ }
+ 
++static bool
++legalize_txf_lod(nir_builder *b, nir_instr *instr, UNUSED void *data)
++{
++   if (instr->type != nir_instr_type_tex)
++      return false;
++
++   nir_tex_instr *tex = nir_instr_as_tex(instr);
++
++   if (tex->op != nir_texop_txf)
++      return false;
++
++   b->cursor = nir_before_instr(instr);
++
++   int lod_index = nir_tex_instr_src_index(tex, nir_tex_src_lod);
++   assert(lod_index >= 0);
++   nir_def *lod = tex->src[lod_index].src.ssa;
++
++   nir_src_rewrite(&tex->src[lod_index].src, nir_i2f32(b, lod));
++
++   return true;
++}
++
+ bool
+ etna_nir_lower_texture(nir_shader *s, struct etna_shader_key *key)
+ {
+@@ -48,5 +70,8 @@ etna_nir_lower_texture(nir_shader *s, struct etna_shader_key *key)
+    NIR_PASS(progress, s, nir_shader_instructions_pass, lower_txs,
+          nir_metadata_control_flow, NULL);
+ 
++   NIR_PASS(progress, s, nir_shader_instructions_pass, legalize_txf_lod,
++      nir_metadata_control_flow, NULL);
++
+    return progress;
+ }
+-- 
+2.49.0
+
diff --git a/debian/patches/austriancoder/0003-etnaviv-nir-Add-support-for-txf-texture-operation.patch b/debian/patches/austriancoder/0003-etnaviv-nir-Add-support-for-txf-texture-operation.patch
new file mode 100644
index 00000000000..50ec8e6bce6
--- /dev/null
+++ b/debian/patches/austriancoder/0003-etnaviv-nir-Add-support-for-txf-texture-operation.patch
@@ -0,0 +1,34 @@
+From ca92f8ada0e2d8bca548265cdedb35fc8c24c993 Mon Sep 17 00:00:00 2001
+From: Christian Gmeiner <cgmeiner@igalia.com>
+Date: Fri, 18 Apr 2025 23:42:14 +0200
+Subject: [PATCH 3/3] etnaviv: nir: Add support for txf texture operation
+
+The src[2] value 0x1100 is set based on observed behavior of the blob driver,
+though its exact meaning remains to be documented.
+
+Passes all dEQP-GLES3.functional.shaders.texture_functions.texelfetch.*
+tests on GC7000.
+
+Signed-off-by: Christian Gmeiner <cgmeiner@igalia.com>
+---
+ src/gallium/drivers/etnaviv/etnaviv_compiler_nir_emit.c | 4 ++++
+ 1 file changed, 4 insertions(+)
+
+diff --git a/src/gallium/drivers/etnaviv/etnaviv_compiler_nir_emit.c b/src/gallium/drivers/etnaviv/etnaviv_compiler_nir_emit.c
+index 08a5ab5fb7b..708f0788b58 100644
+--- a/src/gallium/drivers/etnaviv/etnaviv_compiler_nir_emit.c
++++ b/src/gallium/drivers/etnaviv/etnaviv_compiler_nir_emit.c
+@@ -212,6 +212,10 @@ etna_emit_tex(struct etna_compile *c, nir_texop op, unsigned texid, unsigned dst
+    case nir_texop_txb: inst.opcode = ISA_OPC_TEXLDB; break;
+    case nir_texop_txd: inst.opcode = ISA_OPC_TEXLDD; break;
+    case nir_texop_txl: inst.opcode = ISA_OPC_TEXLDL; break;
++   case nir_texop_txf:
++      inst.opcode = ISA_OPC_TXF;
++      inst.src[2] = etna_immediate_int(0x1100);
++      break;
+    default:
+       compile_error(c, "Unhandled NIR tex type: %d\n", op);
+    }
+-- 
+2.49.0
+
diff --git a/debian/patches/series b/debian/patches/series
index 3532759c8c7..e7ee7301bad 100644
--- a/debian/patches/series
+++ b/debian/patches/series
@@ -7,3 +7,6 @@ gfxstream-check-device-before-using.diff
 gfxstream-refactor-device-init.diff
 gfxstream-follow-the-semantics-desired-by-distro-VK.diff
 drisw-Avoid-crashing-when-swrast_loader-NULL.patch
+austriancoder/0001-etnaviv-isa-Add-txf-instruction.patch
+austriancoder/0002-etnaviv-nir-Legalize-txf-lod-src.patch
+austriancoder/0003-etnaviv-nir-Add-support-for-txf-texture-operation.patch
-- 
2.49.0
EOF
