#!/bin/sh
# #1099032
set -e
patch -p1 << 'EOF'
diff -Nru mesa-25.0.0/debian/patches/bug-1099032.patch mesa-25.0.0/debian/patches/bug-1099032.patch
--- mesa-25.0.0/debian/patches/bug-1099032.patch	1970-01-01 01:00:00.000000000 +0100
+++ mesa-25.0.0/debian/patches/bug-1099032.patch	2025-03-05 18:47:34.000000000 +0100
@@ -0,0 +1,14 @@
+--- a/src/panfrost/lib/pan_layout.c
++++ b/src/panfrost/lib/pan_layout.c
+@@ -37,9 +37,9 @@
+  */
+ uint64_t pan_best_modifiers[PAN_MODIFIER_COUNT] = {
+    DRM_FORMAT_MOD_ARM_AFBC(AFBC_FORMAT_MOD_BLOCK_SIZE_32x8 |
+-                           AFBC_FORMAT_MOD_SPARSE | AFBC_FORMAT_MOD_SPLIT),
++                           AFBC_FORMAT_MOD_SPARSE),
+    DRM_FORMAT_MOD_ARM_AFBC(AFBC_FORMAT_MOD_BLOCK_SIZE_32x8 |
+-                           AFBC_FORMAT_MOD_SPARSE | AFBC_FORMAT_MOD_SPLIT |
++                           AFBC_FORMAT_MOD_SPARSE |
+                            AFBC_FORMAT_MOD_YTR),
+ 
+    DRM_FORMAT_MOD_ARM_AFBC(AFBC_FORMAT_MOD_BLOCK_SIZE_16x16 |
diff -Nru mesa-25.0.0/debian/patches/series mesa-25.0.0/debian/patches/series
--- mesa-25.0.0/debian/patches/series	2025-02-22 17:08:27.000000000 +0100
+++ mesa-25.0.0/debian/patches/series	2025-03-05 18:47:34.000000000 +0100
@@ -1,3 +1,4 @@
 path_max.diff
 src_glx_dri_common.h.diff
 disable_ppc64el_assembly.diff
+bug-1099032.patch
EOF
