#!/bin/sh
set -e
patch -p1 << 'EOF'
diff -Nru meson-1.3.1/debian/patches/crossgirs.patch meson-1.3.1/debian/patches/crossgirs.patch
--- meson-1.3.1/debian/patches/crossgirs.patch	1970-01-01 01:00:00.000000000 +0100
+++ meson-1.3.1/debian/patches/crossgirs.patch	2024-01-15 16:04:15.000000000 +0100
@@ -0,0 +1,31 @@
+--- meson-1.3.1.orig/mesonbuild/modules/__init__.py
++++ meson-1.3.1/mesonbuild/modules/__init__.py
+@@ -96,7 +96,7 @@
+                                                    wanted=wanted, silent=silent, for_machine=for_machine)
+ 
+     def find_tool(self, name: str, depname: str, varname: str, required: bool = True,
+-                  wanted: T.Optional[str] = None) -> T.Union['build.Executable', ExternalProgram, 'OverrideProgram']:
++                  wanted: T.Optional[str] = None, native: bool = True) -> T.Union['build.Executable', ExternalProgram, 'OverrideProgram']:
+         # Look in overrides in case it's built as subproject
+         progobj = self._interpreter.program_from_overrides([name], [])
+         if progobj is not None:
+@@ -108,7 +108,7 @@
+             return ExternalProgram.from_entry(name, prog_list)
+ 
+         # Check if pkgconfig has a variable
+-        dep = self.dependency(depname, native=True, required=False, wanted=wanted)
++        dep = self.dependency(depname, native=native, required=False, wanted=wanted)
+         if dep.found() and dep.type_name == 'pkgconfig':
+             value = dep.get_variable(pkgconfig=varname)
+             if value:
+--- meson-1.3.1.orig/mesonbuild/modules/gnome.py
++++ meson-1.3.1/mesonbuild/modules/gnome.py
+@@ -328,7 +328,7 @@
+         }
+         depname = tool_map[tool]
+         varname = tool.replace('-', '_')
+-        return state.find_tool(tool, depname, varname)
++        return state.find_tool(tool, depname, varname, native=depname != "gobject-introspection-1.0")
+ 
+     @typed_kwargs(
+         'gnome.post_install',
diff -Nru meson-1.3.1/debian/patches/series meson-1.3.1/debian/patches/series
--- meson-1.3.1/debian/patches/series	2023-03-28 12:13:25.000000000 +0200
+++ meson-1.3.1/debian/patches/series	2024-01-15 16:05:28.000000000 +0100
@@ -1,2 +1,3 @@
 1-disable-openmpi.patch
 2-disable-rootdir-test.patch
+crossgirs.patch
EOF
