#!/bin/sh
set -e
# https://bugs.debian.org/1112280
patch -p1 << 'EOF'
From d6d54494bc442925e31a940dda5b2b66bacbc464 Mon Sep 17 00:00:00 2001
From: Johannes Schauer Marin Rodrigues <josch@debian.org>
Date: Thu, 28 Aug 2025 09:20:54 +0200
Subject: [PATCH 1/2] debian/local/plymouth.hook: copy theme files with
 --dereference

Theme authors (and fellow plymouth theme packagers) might prefer to use
symlinks in their themes if the files are identical to what is already
shipped in other plymouth theme packages. Using cp with --dereference
makes sure that if the file is a symlink, the content behind the file is
copied instead of creating an initramfs with broken symlinks in it.

For example there already exist multiple two-step themes and several
which are very similar to the spinner theme. This commit avoids having
to copy files like the throbber or the animation but instead allows
creating a symlink farm to the spinner theme.

This also eases copyright documentation for fellow packagers and reduces
the amount of duplication in the archive.

Added Bonus: if the theme contains a broken symlink, then before this
commit, there was no indication of that problem. With this commit, cp
will error-out if it is unable to dereference the symlink.

Closes: #1112280
---
 debian/local/plymouth.hook | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/debian/local/plymouth.hook b/debian/local/plymouth.hook
index 6a90c04a..0c8416e4 100644
--- a/debian/local/plymouth.hook
+++ b/debian/local/plymouth.hook
@@ -53,11 +53,11 @@ fi
 # copy plugin and images for current theme
 copy_exec "${MODULE}"
 mkdir -p "${DESTDIR}/${THEMES}"
-cp -r "${THEMES}/${THEME_NAME}" "${DESTDIR}/${THEMES}"
+cp -r --dereference "${THEMES}/${THEME_NAME}" "${DESTDIR}/${THEMES}"
 
 if [ -n "${IMAGE_DIR}" ] && [ "${THEMES}/${THEME_NAME}" != "${IMAGE_DIR}" ]
 then
-	cp -r "${IMAGE_DIR}" "${DESTDIR}/${THEMES}"
+	cp -r --dereference "${IMAGE_DIR}" "${DESTDIR}/${THEMES}"
 fi
 
 # copy binaries and base plugins
-- 
2.47.2
EOF
patch -p1 << 'EOF'
From 073f511480cbc185e6924e544f22322afaf88ce3 Mon Sep 17 00:00:00 2001
From: Johannes Schauer Marin Rodrigues <josch@debian.org>
Date: Thu, 28 Aug 2025 09:26:46 +0200
Subject: [PATCH 2/2] debian/local/plymouth.hook: only copy watermark.png if
 the theme does not include it yet

Before this commit, plymouth.hook would overwrite an existing
watermark.png in any theme using the two-step module. This commit allows
theme creators to add their own watermark.png without having it
overridden by plymouth.hook.
---
 debian/local/plymouth.hook | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/debian/local/plymouth.hook b/debian/local/plymouth.hook
index 0c8416e4..08fe8e69 100644
--- a/debian/local/plymouth.hook
+++ b/debian/local/plymouth.hook
@@ -140,9 +140,9 @@ case "${THEME_NAME}" in
 		# for two-step
 		case "$(sed -n 's/^ModuleName=\(.*\)/\1/p' ${THEME})" in
 			two-step)
-				# add watermark.png
+				# add watermark.png if theme didn't ship it
 				logo=/usr/share/desktop-base/debian-logos/logo-text-version-64.png
-				if [ -e $logo ]
+				if [ -e $logo ] && [ ! -e "${DESTDIR}/${IMAGE_DIR}/watermark.png" ]
 				then
 					cp $logo "${DESTDIR}/${IMAGE_DIR}/watermark.png"
 				fi
--
2.47.2
EOF
