#!/bin/sh
set -e

case "$(dpkg-parsechangelog --show-field=Distribution)" in
trixie | reform | trixie-backports) : ;;
*)
	echo "E: unknown distribution in d/changelog: $(dpkg-parsechangelog --show-field=Distribution)" >&2
	exit 1
	;;
esac

cat <<'END' >debian/reform-tools.conffiles
remove-on-upgrade /etc/flash-kernel/ubootenv.d/00reform2_ubootenv
remove-on-upgrade /etc/modprobe.d/reform.conf
END

if dpkg --compare-versions "$(dpkg-parsechangelog --show-field=Version)" gt 1.71-2; then
	# versions after trixie come with their own postinst
	sed -i '/^#DEBHELPER#$/d' debian/reform-tools.postinst
else
	# trixie has no postinst
	cat <<'END' >debian/reform-tools.postinst
#!/bin/sh

action="$1"
last_ver="$2"

set -e

# In case reform-tools is installed or upgraded without the kernel being
# installed or upgraded at the same time, the hooks in /etc/kernel/postinst.d
# or /usr/share/kernel/postinst.d are not getting executed. Run them here
# manually. In the worst case, the scripts get run twice but that should not be
# a problem since they are fast.

for kver in $(linux-version list); do
	# We cannot skip kernel versions, even those for which /boot/dtbs/$kvers
	# already exists because a new reform-tools version might've added a new
	# machine.
	DEB_MAINT_PARAMS=configure /usr/share/kernel/postinst.d/zz-reform-tools "$kver" "/boot/vmlinuz-$kver"
done

END
fi

if [ "$(dpkg-parsechangelog --show-field=Distribution)" = trixie ]; then
	# nothing more than the postinst needs to be patched for trixie
	echo '#DEBHELPER#' >>debian/reform-tools.postinst
	exit 0
fi

# append
cat <<'END' >>debian/reform-tools.postinst

for f in mntre reform_bookworm reform_bookworm-backports; do
  file="/etc/apt/sources.list.d/${f}.sources"
  if [ ! -e "$file" ]; then
    continue
  fi
  if [ "$(stat -c %a "$file")" != "666" ]; then
    # nothing to do
    continue
  fi
  echo "E: $file has insecure permissions 0666 -- setting it to 644..." >&2
  chmod 644 "$file"
done
for f in . firefox firefox/syspref.js motd-full motd-rescue profile.d profile.d/reform.sh profile.d/reform-setup.sh; do
  file="/etc/$f"
  if [ ! -e "$file" ]; then
    continue
  fi
  # only process world-writable files
  if [ -z "$(find "$file" -maxdepth 0 \( \! -type l \) -perm /o+w)" ]; then
    continue
  fi
  echo "E: fixing insecure write permissions of $file" >&2
  chmod go-w "$file"
done

if [ -e /etc/skel ] && [ "$(stat -c %a /etc/skel)" = "777" ]; then
  echo "E: fixing insecure read/write permisions of /etc/skel" >&2
  chmod -R go-w /etc/skel
fi

#DEBHELPER#

[ -n "$last_ver" ] || exit 0        # fresh install
[ "$action" = configure ] || exit 0 # unknown action

# only run on upgrade from 1.59 and earlier
dpkg --compare-versions "$last_ver" le-nl 1.59 || exit 0

# only run on Pocket Reform
MACHINE="$(cat /proc/device-tree/model)"
case "$MACHINE" in
  "MNT Pocket Reform"*) : ;;
  *)
    exit 0
    ;;
esac

config=/etc/default/console-setup
# shellcheck disable=SC1090
oldfont="$(
  . $config
  echo "$FONTFACE"
)"
[ "$oldfont" = "Fixed" ] || exit 0 # do nothing if font is customized
# shellcheck disable=SC1090
oldsize="$(
  . $config
  echo "$FONTSIZE"
)"
[ "$oldsize" = "8x16" ] || exit 0 # do nothing if font is customized

cmdline="$(cat /proc/cmdline)"
case "$cmdline" in
  *fbcon=font:*)
    font=""
    size=""
    ;;
  *)
    font="TerminusBold" # no font set by kernel parameter
    size="16x32"
    ;;
esac

sed -i -e "s/^FONTFACE=.*/FONTFACE=$font/" -e "s/FONTSIZE=.*/FONTSIZE=$size/" $config
dpkg-reconfigure -f noninteractive console-setup
END
chmod +x debian/reform-tools.postinst

if [ "$(dpkg-parsechangelog --show-field=Distribution)" = reform ]; then
	# changes specific to the MNT repo:
	#  - depend on fonts-reform-iosevka-term
	#  - replace firefox-esr with firefox
	#  - replace ezurio-qcacld-2.0-dkms with reform-qcacld2
	patch -p1 <<'END'
--- a/debian/control
+++ b/debian/control
@@ -23,6 +23,7 @@ Depends:
  console-setup,
  debconf,
  debianutils (>= 5.21),
+ fonts-reform-iosevka-term (= 2.3.0-1),
  gpiod,
  jq,
  keyboard-configuration,
@@ -78,7 +79,7 @@ Depends:
  dunst,
  engrampa,
  evince,
- firefox-esr,
+ firefox,
  fonts-font-awesome,
  fonts-inter,
  fonts-jetbrains-mono,
@@ -235,7 +236,7 @@ Depends:
  zstd,
  ${misc:Depends},
 Recommends:
- ezurio-qcacld-2.0-dkms,
+ reform-qcacld2,
  flash-kernel,
  linux-headers-mnt-reform-arm64,
  linux-image-mnt-reform-arm64,
END
fi

if dpkg --compare-versions "$(dpkg-parsechangelog --show-field=Version)" gt 1.71-2; then
	# versions after trixie come with support for RCORE-DSI and verbose hook
	:
else
	# add RCORE-DSI support to trixie
	patch -p1 <<'END'
From e1ba34b61bafea548b4962ffe81f344d0dcf5000 Mon Sep 17 00:00:00 2001
From: Johannes Schauer Marin Rodrigues <josch@debian.org>
Date: Tue, 6 May 2025 18:34:46 +0200
Subject: [PATCH] diff between Debian unstable and MNT repos during the Trixie
 freeze

---
 ...e-for-reform2-rk3588-variant-with-ds.patch | 43 ++++++++++
 ...h-RCORE-RK3588-Module.conf-update-to.patch | 80 +++++++++++++++++++
 ...tup-initramfs-tools-hooks-reform-add.patch | 41 ++++++++++
 debian/patches/series                         |  3 +
 4 files changed, 167 insertions(+)
 create mode 100644 debian/patches/0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch
 create mode 100644 debian/patches/0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch
 create mode 100644 debian/patches/0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch
 create mode 100644 debian/patches/series

diff --git a/debian/patches/0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch b/debian/patches/0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch
new file mode 100644
index 0000000..f809f52
--- /dev/null
+++ b/debian/patches/0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch
@@ -0,0 +1,43 @@
+From 542bc575323915a373f367613b4b6fc5d40378d3 Mon Sep 17 00:00:00 2001
+From: "Lukas F. Hartmann" <lukas@mntre.com>
+Date: Fri, 2 May 2025 20:22:15 +0200
+Subject: [PATCH 1/3] machines: add file for reform2 rk3588 variant with dsi
+ display
+
+---
+ ...Reform 2 with RCORE-DSI RK3588 Module.conf | 23 +++++++++++++++++++
+ 1 file changed, 23 insertions(+)
+ create mode 100644 machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf
+
+diff --git a/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf b/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf
+new file mode 100644
+index 0000000..1fd2c35
+--- /dev/null
++++ b/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf	
+@@ -0,0 +1,23 @@
++# name of the system image file produced by reform-system-image
++SYSIMAGE="reform-system-rk3588-dsi"
++DTBPATH="rockchip/rk3588-mnt-reform2-dsi.dtb"
++# flashing the reform-system-image to emmc also flashes u-boot which might
++# soft-brick the module if something goes wrong
++EMMC_USE=true
++EMMC_BOOT=warn
++SD_BOOT=true
++# name of devices in /dev
++DEV_MMC="mmcblk0"
++DEV_MMC_BOOT0=false
++DEV_SD="mmcblk1"
++DEV_SSD="nvme0n1"
++DEV_USB="sda"
++# the current u-boot hashes from source.mnt.re
++UBOOT_SHA1="4d597f4028120c7c35c4267c9c9bb7d409741d55"
++UBOOT_PROJECT="reform-rk3588-uboot"
++UBOOT_TAG="2024-11-13b"
++# idbloader.img is expected at an offset of 32768 bytes and u-boot follows 8355840 bytes after
++UBOOT_OFFSET=32768
++FLASHBIN_OFFSET=0
++NEED_NONFREE=false
++BOOTARGS="ro no_console_suspend cryptomgr.notests loglevel=3  clk_ignore_unused cma=256M swiotlb=65535  console=tty1"
+-- 
+2.39.5
+
diff --git a/debian/patches/0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch b/debian/patches/0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch
new file mode 100644
index 0000000..dcdc7f9
--- /dev/null
+++ b/debian/patches/0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch
@@ -0,0 +1,80 @@
+From a8fae33f02c1bc09d2c2d71596b4228255cf1f51 Mon Sep 17 00:00:00 2001
+From: Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>
+Date: Tue, 6 May 2025 17:57:38 +0200
+Subject: [PATCH 2/3] machines/MNT * with RCORE RK3588 Module.conf: update to
+ u-boot 2025-05-06
+
+---
+ machines/MNT Pocket Reform with RCORE RK3588 Module.conf | 4 ++--
+ machines/MNT Reform 2 with RCORE RK3588 Module.conf      | 4 ++--
+ machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf  | 4 ++--
+ machines/MNT Reform Next with RCORE RK3588 Module.conf   | 4 ++--
+ 4 files changed, 8 insertions(+), 8 deletions(-)
+
+diff --git a/machines/MNT Pocket Reform with RCORE RK3588 Module.conf b/machines/MNT Pocket Reform with RCORE RK3588 Module.conf
+index 98d63d7..2b84bbd 100644
+--- a/machines/MNT Pocket Reform with RCORE RK3588 Module.conf	
++++ b/machines/MNT Pocket Reform with RCORE RK3588 Module.conf	
+@@ -13,9 +13,9 @@ DEV_SD="mmcblk1"
+ DEV_SSD="nvme0n1"
+ DEV_USB="sda"
+ # the current u-boot hashes from source.mnt.re
+-UBOOT_SHA1="0b8c4d7ef564d79981941a972f6e8569cad3ecdf"
++UBOOT_SHA1="373f14807fe29f4151afc05c8e70bcb8f3313e3c"
+ UBOOT_PROJECT="reform-rk3588-uboot"
+-UBOOT_TAG="2024-11-13b"
++UBOOT_TAG="2025-05-06"
+ # idbloader.img is expected at an offset of 32768 bytes and u-boot follows 8355840 bytes after
+ UBOOT_OFFSET=32768
+ FLASHBIN_OFFSET=0
+diff --git a/machines/MNT Reform 2 with RCORE RK3588 Module.conf b/machines/MNT Reform 2 with RCORE RK3588 Module.conf
+index 9bf4351..a646ec4 100644
+--- a/machines/MNT Reform 2 with RCORE RK3588 Module.conf	
++++ b/machines/MNT Reform 2 with RCORE RK3588 Module.conf	
+@@ -13,9 +13,9 @@ DEV_SD="mmcblk1"
+ DEV_SSD="nvme0n1"
+ DEV_USB="sda"
+ # the current u-boot hashes from source.mnt.re
+-UBOOT_SHA1="4d597f4028120c7c35c4267c9c9bb7d409741d55"
++UBOOT_SHA1="033d8e7539b7558fc2f76ad7833707fda7bf0800"
+ UBOOT_PROJECT="reform-rk3588-uboot"
+-UBOOT_TAG="2024-11-13b"
++UBOOT_TAG="2025-05-06"
+ # idbloader.img is expected at an offset of 32768 bytes and u-boot follows 8355840 bytes after
+ UBOOT_OFFSET=32768
+ FLASHBIN_OFFSET=0
+diff --git a/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf b/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf
+index 1fd2c35..10f804b 100644
+--- a/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf	
++++ b/machines/MNT Reform 2 with RCORE-DSI RK3588 Module.conf	
+@@ -13,9 +13,9 @@ DEV_SD="mmcblk1"
+ DEV_SSD="nvme0n1"
+ DEV_USB="sda"
+ # the current u-boot hashes from source.mnt.re
+-UBOOT_SHA1="4d597f4028120c7c35c4267c9c9bb7d409741d55"
++UBOOT_SHA1="57b19e6eb3e0e46cdb8514c2767bf4fe2f66c067"
+ UBOOT_PROJECT="reform-rk3588-uboot"
+-UBOOT_TAG="2024-11-13b"
++UBOOT_TAG="2025-05-06"
+ # idbloader.img is expected at an offset of 32768 bytes and u-boot follows 8355840 bytes after
+ UBOOT_OFFSET=32768
+ FLASHBIN_OFFSET=0
+diff --git a/machines/MNT Reform Next with RCORE RK3588 Module.conf b/machines/MNT Reform Next with RCORE RK3588 Module.conf
+index 1c40158..b0276f2 100644
+--- a/machines/MNT Reform Next with RCORE RK3588 Module.conf	
++++ b/machines/MNT Reform Next with RCORE RK3588 Module.conf	
+@@ -13,9 +13,9 @@ DEV_SD="mmcblk1"
+ DEV_SSD="nvme0n1"
+ DEV_USB="sda"
+ # the current u-boot hashes from source.mnt.re
+-UBOOT_SHA1="e99c53a0c6490fc9b8c361d0d09516de968b607a"
++UBOOT_SHA1="9a76c872ffcf2da657a8441d4bca192217334cda"
+ UBOOT_PROJECT="reform-rk3588-uboot"
+-UBOOT_TAG="2024-11-13b"
++UBOOT_TAG="2025-05-06"
+ # idbloader.img is expected at an offset of 32768 bytes and u-boot follows 8355840 bytes after
+ UBOOT_OFFSET=32768
+ FLASHBIN_OFFSET=0
+-- 
+2.39.5
+
diff --git a/debian/patches/0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch b/debian/patches/0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch
new file mode 100644
index 0000000..33b99f3
--- /dev/null
+++ b/debian/patches/0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch
@@ -0,0 +1,41 @@
+From 396f905767216b775d6d3764bc89512a37d7e6b4 Mon Sep 17 00:00:00 2001
+From: Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>
+Date: Wed, 7 May 2025 18:52:16 +0200
+Subject: [PATCH 3/3] bin/reform-hw-setup & initramfs-tools/hooks/reform: add
+ MNT Reform 2 with RCORE-DSI RK3588 Module
+
+---
+ bin/reform-hw-setup          | 4 ++++
+ initramfs-tools/hooks/reform | 1 +
+ 2 files changed, 5 insertions(+)
+
+diff --git a/bin/reform-hw-setup b/bin/reform-hw-setup
+index 1d8f785..3f5b073 100755
+--- a/bin/reform-hw-setup
++++ b/bin/reform-hw-setup
+@@ -186,6 +186,10 @@ case "$(cat /proc/device-tree/model)" in
+     init_rk3588
+     init_wm8960
+     ;;
++  "MNT Reform 2 with RCORE-DSI RK3588 Module")
++    init_rk3588
++    init_wm8960
++    ;;
+   "MNT Pocket Reform with RCORE RK3588 Module")
+     init_rk3588
+     init_tlv320aic3100
+diff --git a/initramfs-tools/hooks/reform b/initramfs-tools/hooks/reform
+index a0d4182..4c3898c 100755
+--- a/initramfs-tools/hooks/reform
++++ b/initramfs-tools/hooks/reform
+@@ -40,6 +40,7 @@ case $MACHINE in
+     copy_exec /usr/bin/dmesg
+     ;;
+   "MNT Reform 2 with RCORE RK3588 Module") : ;;
++  "MNT Reform 2 with RCORE-DSI RK3588 Module") : ;;
+   "MNT Pocket Reform with i.MX8MP Module") : ;;
+   "MNT Pocket Reform with BPI-CM4 Module") : ;;
+   "MNT Pocket Reform with RCORE RK3588 Module") : ;;
+-- 
+2.39.5
+
diff --git a/debian/patches/series b/debian/patches/series
new file mode 100644
index 0000000..72f53ec
--- /dev/null
+++ b/debian/patches/series
@@ -0,0 +1,3 @@
+0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch
+0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch
+0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch
-- 
2.39.5
END
	patch -p1 <<'END'
From 12b46cdf07971b5eb6ca11cf3cafcf95bd5b001b Mon Sep 17 00:00:00 2001
From: Johannes Schauer Marin Rodrigues <josch@debian.org>
Date: Sat, 17 May 2025 13:19:22 +0200
Subject: [PATCH] kernel/zz-reform-tools: make verbose

---
 debian/patches/series                    |  1 +
 debian/patches/verbose-kernel-hook.patch | 19 +++++++++++++++++++
 2 files changed, 20 insertions(+)
 create mode 100644 debian/patches/verbose-kernel-hook.patch

diff --git a/debian/patches/series b/debian/patches/series
index 72f53ec..789f89e 100644
--- a/debian/patches/series
+++ b/debian/patches/series
@@ -1,3 +1,4 @@
 0001-machines-add-file-for-reform2-rk3588-variant-with-ds.patch
 0002-machines-MNT-with-RCORE-RK3588-Module.conf-update-to.patch
 0003-bin-reform-hw-setup-initramfs-tools-hooks-reform-add.patch
+verbose-kernel-hook.patch
diff --git a/debian/patches/verbose-kernel-hook.patch b/debian/patches/verbose-kernel-hook.patch
new file mode 100644
index 0000000..11f5809
--- /dev/null
+++ b/debian/patches/verbose-kernel-hook.patch
@@ -0,0 +1,20 @@
+--- a/kernel/zz-reform-tools
++++ b/kernel/zz-reform-tools
+@@ -23,6 +23,9 @@ action="${action%\'}"
+ 
+ set -u
+ 
++echo "I: Now running: $@" >&2
++echo "I: with DEB_MAINT_PARAMS=$DEB_MAINT_PARAMS" >&2
++
+ install_dtbs() {
+   for CONF in /usr/share/reform-tools/machines/*.conf; do
+     # shellcheck disable=SC1090
+@@ -43,6 +45,7 @@ install_dtbs() {
+       echo "W: irregular dtb path: $dtb" >&2
+     fi
+     mkdir -p "/boot/dtbs/$version/$(dirname "$DTBPATH")"
++    echo "I: copying $dtb to /boot/dtbs/$version/$DTBPATH" >&2
+     cp "$dtb" "/boot/dtbs/$version/$DTBPATH"
+   done
+ }
-- 
2.39.5
END
fi
