#!/bin/sh
set -e

case "$(dpkg-parsechangelog --show-field=Distribution)" in
reform)
	# all modifications to reform-tools are stored in the reform-tools/debian
	# directory in the parent directory of this script
	cp -a "$(dirname -- "$0")/../reform-tools/debian" .
	;;
trixie | trixie-backports)
	# trixie has no postinst
	test ! -e debian/reform-tools.postinst
	cat <<'END' >debian/reform-tools.postinst
#!/bin/sh

action="$1"
last_ver="$2"

set -e

# In case reform-tools is installed or upgraded without the kernel being
# installed or upgraded at the same time, the hooks in /etc/kernel/postinst.d
# or /usr/share/kernel/postinst.d are not getting executed. Run them here
# manually. In the worst case, the scripts get run twice but that should not be
# a problem since they are fast.

for kver in $(linux-version list); do
	# We cannot skip kernel versions, even those for which /boot/dtbs/$kvers
	# already exists because a new reform-tools version might've added a new
	# machine.
	DEB_MAINT_PARAMS=configure /usr/share/kernel/postinst.d/zz-reform-tools "$kver" "/boot/vmlinuz-$kver"
done

#DEBHELPER#
END
	chmod +x debian/reform-tools.postinst

	test ! -e debian/patches/series
	mkdir debian/patches
	echo verbose-kernel-hook.patch >debian/patches/series
	cat <<'END' >debian/patches/verbose-kernel-hook.patch
--- a/kernel/zz-reform-tools
+++ b/kernel/zz-reform-tools
@@ -23,6 +23,9 @@ action="${action%\'}"
 
 set -u
 
+echo "I: Now running: $*" >&2
+echo "I: with DEB_MAINT_PARAMS=$DEB_MAINT_PARAMS" >&2
+
 install_dtbs() {
   for CONF in /usr/share/reform-tools/machines/*.conf; do
     # shellcheck disable=SC1090
@@ -43,6 +45,7 @@ install_dtbs() {
       echo "W: irregular dtb path: $dtb" >&2
     fi
     mkdir -p "/boot/dtbs/$version/$(dirname "$DTBPATH")"
+    echo "I: copying $dtb to /boot/dtbs/$version/$DTBPATH" >&2
     cp "$dtb" "/boot/dtbs/$version/$DTBPATH"
   done
 }
END
	;;
*)
	echo "E: unknown distribution in d/changelog: $(dpkg-parsechangelog --show-field=Distribution)" >&2
	exit 1
	;;
esac
