image: debian:bookworm-slim

variables:
  GIT_CLEAN_FLAGS: -ffdx -e demo

build:
  script: |
    set -ex
    if [ -e demo ]; then echo "demo exists"; else echo "demo doesn't exist"; fi
    touch demo
