spec:
  inputs:
    basesuite:
      description: "Debian suite to fetch packages from"
      default: unstable
      options:
        - unstable
        - experimental
    oursuite:
      description: "Suite name of the repository we create"
      default: reform
    mirror:
      description: "Debian mirror to pull packages from"
      default: "http://deb.debian.org/debian"
---

image: debian:unstable-slim

stages:
  - build
  - reprepro

.setup:
  before_script: |
    set -x
    BASESUITE='$[[ inputs.basesuite ]]'
    export BASESUITE
    OURSUITE='$[[ inputs.oursuite ]]'
    export OURSUITE
    MIRROR='$[[ inputs.mirror ]]'
    export MIRROR
    # Do not allow custom builds in the 'reform' namespace as those can
    # potentially taint the repository at https://mntre.com/reform-debian-repo/
    if [ "$CI_SERVER_HOST" = "source.mnt.re" ] && [ "$CI_PROJECT_NAMESPACE" = "reform" ]; then
      if [ "$[[ inputs.basesuite ]]" != "unstable" ]; then
        echo "Refusing to run pipeline in the 'reform' namespace with BASESUITE not set to 'unstable'" >&2
        echo "to avoid accidentally tainting the repository at https://mntre.com/reform-debian-repo." >&2
        echo "Consider running custom pipelines in a fork of reform-debian-packages under your own username instead." >&2
        exit 1
      fi
      if [ "$[[ inputs.oursuite ]]" != "reform" ]; then
        echo "Refusing to run pipeline on the 'reform' namespace with OURSUITE not set to 'reform'" >&2
        echo "to avoid accidentally tainting the repository at https://mntre.com/reform-debian-repo." >&2
        echo "Consider running custom pipelines in a fork of reform-debian-packages under your own username instead." >&2
        exit 1
      fi
    fi
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --no-install-recommends -y install python3 devscripts reprepro sbuild mmdebstrap uidmap mount debhelper debian-keyring quilt pristine-tar rsync git python3-debian faketime python3-jinja2 python3-dacite debian-archive-keyring curl kernel-wedge unzip build-essential dh-python iproute2 arch-test cpio
    useradd --comment build --home-dir /home/build --create-home build
    chown build -R .
    rm -rvf changes buildlogs chdist repo chroot-*.tar
    runuser -u build -- sh -x ./setup.sh
    runuser -u build -- sed -i 's/^Architectures: .*/Architectures: source arm64 armhf i386 amd64/' ./repo/conf/distributions
    runuser -u build -- reprepro --basedir ./repo export
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    runuser -u build -- sh -c 'mkdir -p ~/.config/sbuild'
    runuser -u build -- sh -c 'echo "\$chroot_mode = \"unshare\";\$unshare_mmdebstrap_keep_tarball=1;\$chroot_aliases->{reform} = \"unstable\";push @{\$unshare_mmdebstrap_distro_mangle}, qr/^reform\$/, \"unstable\";1;" > ~/.config/sbuild/config.pl'
    runuser -u build -- sh -c 'mkdir -p changes buildlogs'
    chown build -R .

.build_patched:
  stage: build
  #when: manual
  extends: .setup
  script: |
    set -x
    BASESUITE='$[[ inputs.basesuite ]]'
    export BASESUITE
    OURSUITE='$[[ inputs.oursuite ]]'
    export OURSUITE
    MIRROR='$[[ inputs.mirror ]]'
    export MIRROR
    ## if we are on gitlab CI and if the current branch is NOT main, then
    ## fill the repo with cached results from the last successful run in main
    #for p in patches/*; do
    #  p=${p#patches/}
    #  [ -e "patches/$p" ] || continue
    #  [ -x "patches/$p" ] || continue
    #  if [ -n "${CI_COMMIT_REF_NAME+x}" ] && [ "${CI_COMMIT_REF_NAME:-}" != main ]; then
    #    for variant in cross native; do
    #      if [ "$(curl --silent --output /dev/null --write-out "%{http_code}" --location "$CI_PROJECT_URL/-/jobs/artifacts/main/raw/changes/${p}_${variant}.changes?job=build_patched")" != "200" ]; then
    #        echo "${p}_${variant}.changes is not available" >&2
    #        continue
    #      fi
    #      curl --silent --location "$CI_PROJECT_URL/-/jobs/artifacts/main/raw/changes/${p}_${variant}.changes?job=build_patched" > "changes/${p}_${variant}.changes"
    #      env --chdir=changes dcmd "${p}_${variant}.changes" | while read f; do
    #        echo "downloading $f" >&2
    #        curl --silent --location "$CI_PROJECT_URL/-/jobs/artifacts/main/raw/changes/${f}?job=build_patched" > "changes/${f}"
    #      done
    #      echo "including ${p}_${variant}.changes" >&2
    #      runuser -u build -- reprepro --basedir ./repo include "reform" "changes/${p}_${variant}.changes"
    #    done
    #  fi
    #done
    runuser -u build -- sh -x ./build_patched.sh 2>&1 | ./filter-output
    # move to arch-qualified path
    mv changes "changes-$HOST_ARCH"

build_patched_arm64:
  variables:
    BUILD_ARCH: arm64
    HOST_ARCH: arm64
  extends: .build_patched
  tags:
    - arm64
  artifacts:
    when: always
    paths:
      - output.log
      - changes-arm64
      - buildlogs

build_patched_armhf:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: armhf
    HOST_ARCH: armhf
  extends: .build_patched
  tags:
    - armhf
  artifacts:
    when: always
    paths:
      - output.log
      - changes-armhf
      - buildlogs

build_patched_i386:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: i386
    HOST_ARCH: i386
  extends: .build_patched
  tags:
    - i386
  artifacts:
    when: always
    paths:
      - output.log
      - changes-i386
      - buildlogs

build_patched_amd64:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: amd64
    HOST_ARCH: amd64
  extends: .build_patched
  tags:
    - amd64
  artifacts:
    when: always
    paths:
      - output.log
      - changes-amd64
      - buildlogs

build_custom:
  stage: build
  variables:
    BUILD_ARCH: arm64
    HOST_ARCH: arm64
  #when: manual
  extends: .setup
  tags:
    - arm64
  artifacts:
    when: always
    paths:
      - output.log
      - changes-custom
      - buildlogs
      - fonts-reform-iosevka-term_2.3.0.1.dsc
      - fonts-reform-iosevka-term_2.3.0.1.tar.xz
      - fonts-reform-iosevka-term_2.3.0.1_arm64.buildinfo
      - fonts-reform-iosevka-term_2.3.0.1_arm64.changes
      - fonts-reform-iosevka-term_2.3.0.1_arm64.deb
  script: |
    set -exuo pipefail
    BASESUITE='$[[ inputs.basesuite ]]'
    export BASESUITE
    OURSUITE='$[[ inputs.oursuite ]]'
    export OURSUITE
    MIRROR='$[[ inputs.mirror ]]'
    export MIRROR
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --yes install --no-install-recommends equivs
    runuser -u build -- sh -x ./build_custom.sh 2>&1 | ./filter-output
    mv changes changes-custom
  after_script: |
    echo "BASESUITE: $[[ inputs.basesuite ]]"
    echo "OURSUITE: $[[ inputs.oursuite ]]"

.build_linux:
  stage: build
  #when: manual
  extends: .setup
  script: |
    set -x
    BASESUITE='$[[ inputs.basesuite ]]'
    export BASESUITE
    OURSUITE='$[[ inputs.oursuite ]]'
    export OURSUITE
    MIRROR='$[[ inputs.mirror ]]'
    export MIRROR
    echo "MIRROR: $[[ inputs.mirror ]]" >&2
    # gitlab has pipefail turned on by default, so the below will fail if
    # build.sh fails despite the command being piped to filter-output.
    runuser -u build -- sh -xc '. ./common.sh; cd linux; . ./build.sh' 2>&1 | ./filter-output
    # move to arch-qualified path
    mv changes "changes-$HOST_ARCH"
    # kernel specific checks only on arm64
    if [ "$HOST_ARCH" != "arm64" ]; then
      exit 0
    fi
    for module in 'kernel/drivers/gpu/drm/imx\(/cdns\)\?/cdns_mhdp_imx.ko' \
                  'kernel/drivers/gpu/drm/bridge/cadence/cdns-mhdp8546.ko' \
                  'kernel/drivers/net/mdio/mdio-mux-meson-g12a.ko'; do
      # since kernel 6.19, modules are in the linux-modules-* package
      found=0
      for p in "changes-$HOST_ARCH"/linux-image-*-mnt-reform-arm64_*_arm64.deb \
               "changes-$HOST_ARCH"/linux-modules-*-mnt-reform-arm64_*_arm64.deb; do
        [ -e "$p" ] || continue
        if dpkg-deb -c "$p" | grep "$module"; then
          found=1
          break
        fi
      done
      if [ "$found" -eq 0 ]; then
        echo "$module missing" >&2
        exit 1
      else
        echo "$module found" >&2
      fi
    done
    for dtb in amlogic/meson-g12b-bananapi-cm4-mnt-pocket-reform.dtb freescale/imx8mp-mnt-pocket-reform.dtb freescale/imx8mq-mnt-reform2.dtb freescale/imx8mq-mnt-reform2-hdmi.dtb amlogic/meson-g12b-bananapi-cm4-mnt-reform2.dtb freescale/imx8mp-mnt-reform2.dtb freescale/fsl-ls1028a-mnt-reform2.dtb rockchip/rk3588-mnt-reform2.dtb; do
      # since kernel 6.19, dtbs are in the linux-base-* package
      found=0
      for p in "changes-$HOST_ARCH"/linux-image-*-mnt-reform-arm64_*_arm64.deb \
               "changes-$HOST_ARCH"/linux-base-*-mnt-reform-arm64_*_arm64.deb; do
        [ -e "$p" ] || continue
        if dpkg-deb -c "$p" | grep "/${dtb}\$"; then
          found=1
          break
        fi
      done
      if [ "$found" -eq 0 ]; then
        echo "$dtb missing" >&2
        exit 1
      else
        echo "$dtb found" >&2
      fi
    done
    for f in "changes-$HOST_ARCH"/linux-image-arm64_*_arm64.deb "changes-$HOST_ARCH"/linux-headers-arm64_*_arm64.deb; do
      if [ ! -e "$f" ]; then
        echo "$f does not exist" >&2
        exit 1
      fi
    done

  after_script: |
    if [ $CI_JOB_STATUS != 'success' ]; then
      # The linux log is ~100 MB large so much too big to be stored by gitlab
      # as the job log. To avoid having to manually browse the artifacts and
      # download the log, grep for common error indicators in the log and
      # display the result here.
      grep -B1 -A3 --color -P '([^"]error:|Error|[^_W]ERROR|Waiting for unfinished jobs)' linux/linux_*_"${HOST_ARCH}"-*.build
      exit 1
    fi
    echo "BASESUITE: $[[ inputs.basesuite ]]"
    echo "OURSUITE: $[[ inputs.oursuite ]]"

build_linux_arm64:
  variables:
    BUILD_ARCH: arm64
    HOST_ARCH: arm64
  extends: .build_linux
  tags:
    - arm64
  artifacts:
    when: always
    paths:
      - output.log
      - changes-arm64
      - linux/linux_*_arm64-*.build

build_linux_armhf:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: armhf
    HOST_ARCH: armhf
  extends: .build_linux
  tags:
    - armhf
  artifacts:
    when: always
    paths:
      - output.log
      - changes-armhf
      - linux/linux_*_armhf-*.build

build_linux_i386:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: i386
    HOST_ARCH: i386
  extends: .build_linux
  tags:
    - i386
  artifacts:
    when: always
    paths:
      - output.log
      - changes-armhf
      - linux/linux_*_armhf-*.build

build_linux_amd64:
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_REF_NAME == "main"
  variables:
    BUILD_ARCH: amd64
    HOST_ARCH: amd64
  extends: .build_linux
  tags:
    - amd64
  artifacts:
    when: always
    paths:
      - output.log
      - changes-amd64
      - linux/linux_*_amd64-*.build

dtbs_check:
  stage: build
  tags:
    - arm64
  needs:
    - job: build_linux_arm64
      artifacts: true
  script: |
    set -exuo pipefail
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --yes install --no-install-recommends gcc-aarch64-linux-gnu build-essential bison flex device-tree-compiler git ca-certificates xz-utils libssl-dev bc dt-schema
    dpkg -x ./changes-arm64/linux-source-*.deb ./
    dpkg -x ./changes-arm64/linux-config-*.deb ./
    tar xfJ usr/src/linux-source-*.tar.xz
    cd linux-source-*
    xz --decompress --to-stdout ../usr/src/linux-config-*/config.arm64_none_*arm64.xz > .config
    for dtb in \
      amlogic/meson-g12b-bananapi-cm4-mnt-pocket-reform.dtb \
      freescale/imx8mp-mnt-pocket-reform.dtb \
      freescale/imx8mq-mnt-reform2.dtb \
      freescale/imx8mq-mnt-reform2-hdmi.dtb \
      amlogic/meson-g12b-bananapi-cm4-mnt-reform2.dtb \
      freescale/imx8mp-mnt-reform2.dtb \
      freescale/fsl-ls1028a-mnt-reform2.dtb \
      rockchip/rk3588-mnt-reform2.dtb; do
      set +x
      echo =================================================================
      echo "    $dtb"
      echo =================================================================
      set -x
      make CHECK_DTBS=y "$dtb"
    done

build_qcacld:
  stage: build
  extends: .setup
  tags:
    - arm64
  needs:
    - job: build_linux_arm64
      artifacts: true
  script: |
    set -exuo pipefail
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --yes install --no-install-recommends gcc-aarch64-linux-gnu build-essential bison flex device-tree-compiler git ca-certificates xz-utils libssl-dev bc sbuild

    if [ -z ${SOURCE_DATE_EPOCH:+x} ] && git -C . rev-parse 2>/dev/null; then
      SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)
    else
      : "${SOURCE_DATE_EPOCH:=$(date --utc +%s)}"
    fi
    export SOURCE_DATE_EPOCH

    KERNEL_ABINAME=$(dpkg-deb --field changes-arm64/linux-image-*-mnt-reform-arm64_*_arm64.deb Package)
    KERNEL_ABINAME=${KERNEL_ABINAME##linux-image-}

    git clone --depth=1 --branch=binary-deb https://source.mnt.re/reform/qcacld2.git

    env --chdir=qcacld2 ./createdeb.sh "$KERNEL_ABINAME" "$(pwd)"/changes-arm64/linux-source-*.deb

    chown build -R .
    runuser -u build -- env --chdir=qcacld2 sbuild --verbose --no-run-lintian --no-run-autopkgtest --extra-package "$(pwd)"/changes-arm64/linux-source-*.deb --extra-package "$(pwd)"/changes-arm64/linux-config-*.deb --no-clean-source
  artifacts:
    when: always
    paths:
      - "reform-qcacld2*.deb"
      - "*.buildinfo"
      - "*.changes"

reprepro:
  stage: reprepro
  extends: .setup
  tags:
    - arm64
  dependencies:
    - build_patched_arm64
    - build_patched_armhf
    - build_patched_amd64
    - build_patched_i386
    - build_custom
    - build_linux_arm64
    - build_linux_armhf
    - build_linux_amd64
    - build_linux_i386
    - build_qcacld
  artifacts:
    when: always
    paths:
      - repo
      - variables.sh
  script: |
    set -x
    BASESUITE='$[[ inputs.basesuite ]]'
    export BASESUITE
    OURSUITE='$[[ inputs.oursuite ]]'
    export OURSUITE
    MIRROR='$[[ inputs.mirror ]]'
    export MIRROR
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --no-install-recommends -y install reprepro python3 devscripts
    runuser -u build -- sh -x ./reprepro.sh
    {
      echo "CI_PROJECT_NAMESPACE=\"$CI_PROJECT_NAMESPACE\"";
      echo "CI_COMMIT_BRANCH=\"$CI_COMMIT_BRANCH\"";
      echo "CI_COMMIT_REF_NAME=\"$CI_COMMIT_REF_NAME\"";
      echo "BASESUITE=\"$[[ inputs.basesuite ]]\"";
      echo "OURSUITE=\"$[[ inputs.oursuite ]]\"";
    } | tee variables.sh
  after_script: |
    echo "To use the artifacts of this job as an apt source, add this to your /etc/apt/sources.list:" >&2
    echo "deb [trusted=yes arch=arm64] https://$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/reform-debian-packages/-/jobs/$CI_JOB_ID/artifacts/raw/repo $[[ inputs.oursuite ]] main"
