#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "reform-standby has to be run as root / using sudo."
  exit
fi

WIFI=wlp1s0

# configure UARTs as wakeup sources
echo enabled > /sys/devices/platform/soc@0/30800000.bus/30860000.serial/tty/ttymxc0/power/wakeup
echo enabled > /sys/devices/platform/soc@0/30800000.bus/30890000.serial/tty/ttymxc1/power/wakeup
echo enabled > /sys/devices/platform/soc@0/30800000.bus/30880000.serial/tty/ttymxc2/power/wakeup

if [ -e /sys/class/net/$WIFI ]
then
  echo "Disconnecting Wi-Fi ($WIFI)..."
  ifconfig $WIFI down
fi

echo Entering standby in 3...
sleep 1
echo 2...
sleep 1
echo 1...
sleep 1

sync
echo mem >/sys/power/state

# reset wifi
if [ -e /sys/class/net/$WIFI ]
then
  echo "Resetting Wi-Fi ($WIFI)..."
  sleep 1
  echo 1 > /sys/devices/platform/soc@0/33800000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/reset
  sleep 1
  ifconfig $WIFI up
  echo Done.
fi
